blog/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/comment/new/', views.comment_new, name='comment_new'),
    path('<int:post_pk>/comment/<int:comment_pk>/edit/', views.comment_edit, name='comment_edit'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comment/<int:comment_pk>/reply/', views.comment_reply, name='comment_reply'),
    path('<int:post_pk>/comment/<int:comment_pk>/reply/<int:reply_pk>/edit/', views.reply_edit, name='reply_edit'),
    path('<int:post_pk>/comment/<int:comment_pk>/reply/<int:reply_pk>/delete/', views.reply_delete, name='reply_delete'),
]



blog/blogbase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('blog/', include(('blog.urls', 'blog'))),
    path('accounts/', include('accounts.urls')),
    prefix_default_language=True,
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/base.html
{% load static %} {% load django_bootstrap5 %} {% load i18n %}
<!-- static정적파일 django_bootstrap5부트스트립5 적용 i18n 번역-->
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Blog Post - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <!-- 번역될 곳은  {% trans "번역될 언어" %}-->
            <a class="navbar-brand" href="#!">{% trans "블로그" %}</a>
            <!-- 영한 전환  form-->
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <select name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                        {{ language.name_local }} [{{ language.code }}]
                    </option>
                {% endfor %}
                </select>
                <input class="navbar-brand navbar-expand-lg navbar-dark bg-dark" type="submit" value="Change" />
            </form>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:post_list' %}">{% trans "블로그" %}</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:profile' %}">{% trans "프로필" %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{% trans "로그아웃" %}</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">{% trans "로그인" %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">{% trans "회원가입" %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; 2023</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>