blog/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/comment/new/', views.comment_new, name='comment_new'),
    path('<int:post_pk>/comment/<int:comment_pk>/edit/', views.comment_edit, name='comment_edit'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comment/<int:comment_pk>/reply/', views.comment_reply, name='comment_reply'),
    path('<int:post_pk>/comment/<int:comment_pk>/reply/<int:reply_pk>/edit/', views.reply_edit, name='reply_edit'),
    path('<int:post_pk>/comment/<int:comment_pk>/reply/<int:reply_pk>/delete/', views.reply_delete, name='reply_delete'),
]



blog/blogbase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('blog/', include(('blog.urls', 'blog'))),
    path('accounts/', include('accounts.urls')),
    prefix_default_language=True,
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/models.py
from django.db import models
from django.conf import settings

# 태그에 대한 모델을 정의합니다.
class Tag(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    
    def __str__(self):
        return self.name

# 게시글에 대한 모델을 정의합니다.
class Post(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    # 게시글의 내용입니다.
    content = models.TextField()
    thumb_image = models.ImageField(
        upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(
        upload_to='blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    view_count = models.PositiveIntegerField(default=0)
    # 게시글의 태그, Tag 모델을 참조합니다. 선택적 필드입니다.
    tags = models.ManyToManyField(Tag, blank=True)

    # 게시글의 제목을 반환하는 메서드입니다.
    def __str__(self):
        return self.title
    
    # 게시글의 절대 URL을 반환하는 메서드입니다.
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
# 댓글에 대한 모델을 정의합니다.
class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
    )
    user  = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    # 댓글에 대한 대댓글
    parent_comment = models.ForeignKey(
        'self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True
        )
    # 댓글의 내용입니다.
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    content = models.TextField()
    
    
    def __str__(self):
        return f"Comment #{self.id}: {self.content[:50]}"
    

blog/blog/forms.py
from django import forms
from .models import Post, Comment, Tag


class PostForm(forms.ModelForm):
    tags = forms.CharField()

    class Meta:
        model = Post
        fields = ['title', 'content', 'thumb_image', 'file_upload', 'tags'] 

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.save()
        return instance


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']


blog/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, CreateView
from .models import Post, Comment, Tag
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.shortcuts import render

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q', '')
        if q:
            qs = qs.filter(Q(title__icontains=q) | Q(tags__name__icontains=q)).distinct()
        return qs

post_list = PostListView.as_view()


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        post = form.save(commit=False)
        post.save()
        video = form.save(commit=True)
        video.user = self.request.user
        tag_names = form.cleaned_data['tags']
        if tag_names:  
            for tag_name in tag_names.split(','):
                tag, _ = Tag.objects.get_or_create(name=tag_name.strip())
                post.tags.add(tag)

        return super().form_valid(form)

post_new = PostCreateView.as_view()


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.object).order_by('-created_at')
        context['comment_form'] = CommentForm()
        return context
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        post = Post.objects.get(pk=pk)
        post.view_count += 1
        post.save()
        return super().get_object(queryset)

post_detail = PostDetailView.as_view()


class PostUpdateView(UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/form.html'

    def test_func(self): 
        return self.get_object().user == self.request.user

post_edit = PostUpdateView.as_view()


class PostDeleteView(UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

    def test_func(self):
        return self.get_object().user == self.request.user

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        return get_object_or_404(Post, id=post.id)

post_delete = PostDeleteView.as_view()


# 댓글 생성 뷰
class CommentNewView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('blog:post_detail', pk)
        return render(request, 'blog/form.html', {'form': form})

    def get(self, request):
        form = CommentForm()
        return render(request, 'blog/form.html', {'form': form})

comment_new = CommentNewView.as_view()


# 댓글 수정 뷰
class CommentUpdateView(UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/form.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Comment, post__pk=self.kwargs['post_pk'], pk=self.kwargs['comment_pk'])

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.post.pk})

    def test_func(self): 
        return self.get_object().user == self.request.user

comment_edit = CommentUpdateView.as_view()


# 댓글 삭제 뷰
class CommentDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'blog/post_confirm_delete.html'
    
    def get_object(self, queryset=None):
        return get_object_or_404(Comment, post__pk=self.kwargs['post_pk'], pk=self.kwargs['comment_pk'])

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.post.pk})

    def test_func(self): 
        return self.get_object().user == self.request.user

comment_delete = CommentDeleteView.as_view()


class CommentReplyView(LoginRequiredMixin, CreateView):
    def post(self, request, post_pk, comment_pk):
        post = get_object_or_404(Post, pk=post_pk)
        comment = get_object_or_404(Comment, pk=comment_pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.post = post
            reply.comment = comment
            reply.user = request.user
            reply.save()
            return redirect('blog:post_detail', post_pk)
        return render(request, 'blog/form.html', {'form': form})

    def get(self, request, post_pk, comment_pk):
        form = CommentForm()
        return render(request, 'blog/form.html', {'form': form, 'post_pk': post_pk, 'comment_pk': comment_pk})

comment_reply = CommentReplyView.as_view()


# 답글 수정 뷰
class ReplyUpdateView(UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/form.html'

    def get_object(self, queryset=None):
        return get_object_or_404(self, comment__post__pk=self.kwargs['post_pk'], comment__pk=self.kwargs['comment_pk'], pk=self.kwargs['reply_pk'])

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.post.pk})

    def test_func(self): 
        return self.get_object().user == self.request.user

reply_edit = ReplyUpdateView.as_view()


# 답글 삭제 뷰
class ReplyDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'blog/post_confirm_delete.html'

    def get_object(self, queryset=None):
        return get_object_or_404(self, comment__post__pk=self.kwargs['post_pk'], comment__pk=self.kwargs['comment_pk'], pk=self.kwargs['reply_pk'])

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.post.pk})

    def test_func(self): 
        return self.get_object().user == self.request.user

reply_delete = ReplyDeleteView.as_view()


blog/templates/blog/form.html
{% extends 'base.html' %} {% block content %} {% load static %}

<section class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit">
            </form>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<section class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <form method="post">
                <h3>게시물 삭제</h3>
                {% csrf_token %}
                <p>글을 삭제하시겠습니까?</p>
                <input type="submit" value="네!" class="btn btn-primary">

            </form>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <article>
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{object.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">{{post.created_at}}</div>
                    <!-- Post categories-->
                    {% for tag in post.tags.all %}
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{tag.name}}</a>{% endfor %}
                    <p><small>조회수 : {{post.view_count}}</small></p>
                </header>
                <!-- 이미지-->
                {% if post.thumb_image %}
                <figure class="mb-4"><small><img class="img-fluid rounded" src="{{post.thumb_image.url}}" alt="..." /></figure></small> {% endif %} {% if post.file_upload %}
                    <figure class="mb-4"><video src="{{post.file_upload.url}}" controls></video></figure> {% endif %}
                    <!-- 내용-->
                    <section class="mb-5">
                        <p class="fs-5 mb-4">{{object.content}}</p>
                    </section>
            </article>

            <!-- 댓글 section-->
            <section class="mb-5">
                <!-- 댓글 form-->
                <form id="commentForm" action="{% url 'blog:comment_new' post.pk %}" method="post">
                    {% csrf_token %} {{ comment_form.media }} {{ comment_form.as_p }}
                    <input type="submit" value="댓글 작성" style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">
                </form>
                {% for comment in post.comments.all %}
                <div class="card bg-light">
                    <div class="card-body">
                        <div class="d-flex mb-4">
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold">{{comment.user}}</div><span class="small">- {{comment.created_at}}</span> {% if user == comment.user %}<br>
                                <a href="{% url 'blog:comment_edit' post.pk comment.pk %}">수정</a>
                                <div id="deleteButton-{{ comment.pk }}">
                                    <a href="{% url 'blog:comment_delete' post.pk comment.pk %}">삭제</a>
                                </div>{% endif %}
                                <p class="small mb-0">
                                    {{comment.content}}
                                </p>
                                {% if user.is_authenticated %}
                                <!-- 대댓글 버튼 Reply -->
                                <button onclick="toggleButtons(this, '{{ comment.pk }}')" style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">Reply</button>
                                <form id="replyForm-{{ comment.pk }}" style="display: none;" action="{% url 'blog:comment_reply' post.pk comment.pk %}" method="post">
                                    {% csrf_token %} {{ reply_form.as_p }}
                                    <button type="submit" class="btn btn-outline-primary btn-sm " style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">(대댓글)작성</button>
                                    <button type="" class="btn btn-outline-primary btn-sm" style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">취소</button>
                                </form>
                                {% endif %}

                                <!-- 대댓글-->
                                {% for reply in comment.replies.all %}
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">{{reply.user}}</div>
                                        <p class="text-muted small mb-0">{{reply.created_at}}</p> {{reply.content}} {% if user == reply.user %}<br>
                                        <a href="{% url 'blog:reply_edit' post.pk comment.pk reply.pk %}"><i class="fas fa-reply fa-xs"></i><span class="small">수정</span></a>
                                        <a href="{% url 'blog:reply_delete' post.pk comment.pk reply.pk %}"><i class="fas fa-reply fa-xs" ></i><span class="small">삭제</span></a> {%endif %}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </section>

            <a href="{% url 'blog:post_list' %}" style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">목록</a> {% if user == post.user %}
            <a href="{% url 'blog:post_edit' post.pk %}" style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">수정</a>
            <a href="{% url 'blog:post_delete' post.pk %}" style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">삭제</a> {% endif %}

            <script>
                function toggleButtons(button, commentId) {
                    let parentDiv = button.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode;
                    let replyForm = parentDiv.querySelector('#replyForm-' + commentId);

                    if (replyForm.style.display === 'none') {
                        replyForm.style.display = 'block';
                    } else {
                        replyForm.style.display = 'none';
                    }
                }
            </script>
            {% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<h1 class="text-center">{% trans "Post List" %}</h1>
<!-- 검색 기능 추가 -->

<div class="input-group mb-4">
    <form action="" method="GET">
        <input class="form-control" type="text" name="q" value="{{ request.GET.q }}" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
        <input class="btn btn-primary" id="button-search" type="submit" value="검색">
    </form>
</div>
<div class="mb-4">
    <a href="{% url 'blog:post_new' %}" style="background-color: #007BFF; color: white; padding: 5px 10px; border: none; border-radius: 5px;">{% trans "업로드" %}</a>
</div>

<table class="table table-hover table-bordered mb-4">
    <thead>
        <tr class="text-center">
            <th>{% trans "제목" %}</th>
            <th>{% trans "작성자" %}</th>
            <th>{% trans "날짜" %}</th>
            <th>{% trans "조회수" %}</th>
        </tr>
    </thead>
    <tbody class="text-center">
        {% for post in post_list %}
        <tr>
            <td>{{ post.get_language_display }} <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</td>
            <td><small>{{ post.user }}</small></td>
            <td><small>{{ post.created_at }}</small></td>
            <td><small>{{post.view_count}}</small></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">Empty</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}